"""SQL statements shared by database examples."""

CREATE_USER_INFO_TABLE = """
CREATE TABLE IF NOT EXISTS user_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    username VARCHAR(150) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
"""

CREATE_USER_SESSIONS_TABLE = """
CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_info(id) ON DELETE CASCADE,
    refresh_token_hash TEXT UNIQUE NOT NULL,
    refresh_jti TEXT UNIQUE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ
)
"""

INSERT_USER = """
INSERT INTO user_info (username, password_hash)
VALUES (%s, %s)
RETURNING id, username, extra, created_at, updated_at
"""

SELECT_USER_BY_USERNAME = """
SELECT id, username, extra, created_at, updated_at
FROM user_info
WHERE username = %s
"""

SELECT_USER_WITH_PASSWORD_HASH_BY_USERNAME = """
SELECT id, username, password_hash, extra, created_at, updated_at
FROM user_info
WHERE username = %s
"""

UPDATE_USER_PASSWORD = """
UPDATE user_info
SET password_hash = %s, updated_at = NOW()
WHERE username = %s
RETURNING id, username, extra, created_at, updated_at
"""

DELETE_USER_BY_USERNAME = """
DELETE FROM user_info
WHERE username = %s
"""

INSERT_USER_SESSION = """
INSERT INTO user_sessions (user_id, refresh_token_hash, refresh_jti, expires_at)
VALUES (%s, %s, %s, %s)
RETURNING id, user_id, refresh_jti, revoked, expires_at, created_at, revoked_at
"""

SELECT_ACTIVE_SESSION_BY_REFRESH_TOKEN_HASH = """
SELECT
    s.id,
    s.user_id,
    s.refresh_jti,
    s.revoked,
    s.expires_at,
    s.created_at,
    s.revoked_at,
    u.username
FROM user_sessions s
JOIN user_info u ON u.id = s.user_id
WHERE s.refresh_token_hash = %s
  AND s.revoked = FALSE
  AND s.expires_at > NOW()
"""

REVOKE_SESSION_BY_REFRESH_TOKEN_HASH = """
UPDATE user_sessions
SET revoked = TRUE, revoked_at = NOW()
WHERE refresh_token_hash = %s
  AND revoked = FALSE
"""

REVOKE_ALL_USER_SESSIONS_BY_USERNAME = """
UPDATE user_sessions
SET revoked = TRUE, revoked_at = NOW()
WHERE user_id = (SELECT id FROM user_info WHERE username = %s)
  AND revoked = FALSE
"""

SELECT_USER_SESSIONS_BY_USERNAME = """
SELECT
    s.id,
    s.user_id,
    s.refresh_jti,
    s.revoked,
    s.expires_at,
    s.created_at,
    s.revoked_at
FROM user_sessions s
JOIN user_info u ON u.id = s.user_id
WHERE u.username = %s
ORDER BY s.created_at DESC
"""
